jhsd_0001_base = {
    "C0": {"classification": "MI", "name": "国民健康保険"},
    "PI": {"classification": "PI", "name": "公害医療"},
    "LI": {"classification": "LI", "name": "労災"},
    "TI": {"classification": "TI", "name": "自賠"},
    "PS": {"classification": "PS", "name": "公務員災害"},
    "OE": {"classification": "OE", "name": "自費（保険なし）"},
    "D0": {"classification": "PE", "name": "地方公費"},
    "OT": {"classification": "OT", "name": "その他"},
}
jhsd_0001_ext = {
    # NOTE: The keys are '法別番号'
    # 国民健康保険
    "67": {"classification": "MI", "name": "国民健康保険法による退職者医療"},
    # 社会保険制度
    "01": {
        "classification": "MI",
        "name": "政府管掌健康保険（日雇特例被保険者の保険を除く。",
    },
    "02": {"classification": "MI", "name": "船員保険"},
    "03": {"classification": "MI", "name": "一般療養"},
    "04": {"classification": "MI", "name": "特別療養費"},
    "06": {"classification": "MI", "name": "組合管掌健康保険"},
    "07": {
        "classification": "MI",
        "name": "防衛省職員給与法による自衛官等の療養の給付",
    },
    "39": {
        "classification": "MI",
        "name": "高齢者の医療の確保に関する法律による療養の給付",
    },
    "31": {"classification": "MI", "name": "国家公務員共済組合"},
    "32": {"classification": "MI", "name": "地方公務員等共済組合"},
    "33": {"classification": "MI", "name": "警察共済組合"},
    "34": {"classification": "MI", "name": "公立学校共済組合"},
    "63": {"classification": "MI", "name": "特定健康保険組合"},
    "72": {"classification": "MI", "name": "国家公務員特定共済組合"},
    "73": {"classification": "MI", "name": "地方公務員等特定共済組合"},
    "74": {"classification": "MI", "name": "警察特定共済組合"},
    "75": {"classification": "MI", "name": "公立学校特定共済組合"},
    # 公費負担医療制度
    "10": {"classification": "PE", "name": "結核患者の適正医療"},
    "11": {"classification": "PE", "name": "結核患者の入院"},
    "12": {"classification": "PE", "name": "生活保護法による医療扶助（法第15条関係）"},
    "13": {"classification": "PE", "name": "療養の給付"},
    "14": {"classification": "PE", "name": "更生医療"},
    "15": {"classification": "PE", "name": "更生医療（法第５条関係）"},
    "16": {"classification": "PE", "name": "育成医療（法第５条関係）"},
    "17": {"classification": "PE", "name": "療育の給付（法第20条関係）"},
    "18": {"classification": "PE", "name": "認定疾病医療"},
    "19": {"classification": "PE", "name": "一般疾病医療費（法第18条関係）"},
    "20": {"classification": "PE", "name": "措置入院"},
    "21": {"classification": "PE", "name": "精神通院医療"},
    "22": {
        "classification": "PE",
        "name": "麻薬及び向精神薬取締法による入院措置（法第58条の８関係）",
    },
    "23": {"classification": "PE", "name": "母子保健法による養育医療（法第20条関係）"},
    "24": {
        "classification": "PE",
        "name": "療養介護医療（法第70条関係）及び基準該当療養介護医療（法第71条関係）",
    },
    "25": {
        "classification": "PE",
        "name": "中国残留邦人等の円滑な帰国の促進及び永住帰国後の自立の支援に関する法律第14条第４項に規定する医療支援給付",
    },
    "28": {"classification": "PE", "name": "一類感染症等の患者の入院(法第37条関係)"},
    "29": {"classification": "PE", "name": "新感染症の患者の入院"},
    "30": {
        "classification": "PE",
        "name": "心神喪失等の状態で重大な他害行為を行った者の医療及び観察等に関する法律による医療の実施に係る医療の給付",
    },
    "51": {
        "classification": "PE",
        "name": "特定疾患治療費、先天性血液凝固因子障害等治療費、水俣病総合対策費の国庫補助による療養費及び研究治療費、茨城県神栖町における有機ヒ素化合物による環境汚染及び健康被害に係る緊急措度置事業要綱による医療費及びメチル水銀の健康影響による治療研究費",
    },
    "52": {
        "classification": "PE",
        "name": "児童福祉法による小児慢性特定疾患治療研究事業に係る医療の給付（法第21条の５関係）",
    },
    "53": {"classification": "PE", "name": "児童福祉法の措置等に係る医療の給付"},
    "66": {
        "classification": "PE",
        "name": "石綿による健康被害の救済に関する法律による医療費の支給（法第４条関係）",
    },
    "79": {"classification": "PE", "name": "障害児施設医療（法第24条の20関係）"},
}
jhsd_0001 = {
    **jhsd_0001_base,
    **jhsd_0001_ext,
}

jhsd_0002 = {
    "OJ": "職務上",
    "LS": "下船",
    "CC": "通勤災害",
    "K1": "継続",
    "K2": "任意継続",
    "K3": "特別療養",
    "01": "北海道",
    "02": "青森県",
    "03": "岩手県",
    "04": "宮城県",
    "05": "秋田県",
    "06": "山形県",
    "07": "福島県",
    "08": "茨城県",
    "09": "栃木県",
    "10": "群馬県",
    "11": "埼玉県",
    "12": "千葉県",
    "13": "東京都",
    "14": "神奈川県",
    "15": "新潟県",
    "16": "富山県",
    "17": "石川県",
    "18": "福井県",
    "19": "山梨県",
    "20": "長野県",
    "21": "岐阜県",
    "22": "静岡県",
    "23": "愛知県",
    "24": "三重県",
    "25": "滋賀県",
    "26": "京都府",
    "27": "大阪府",
    "28": "兵庫県",
    "29": "奈良県",
    "30": "和歌山県",
    "31": "鳥取県",
    "32": "島根県",
    "33": "岡山県",
    "34": "広島県",
    "35": "山口県",
    "36": "徳島県",
    "37": "香川県",
    "38": "愛媛県",
    "39": "高知県",
    "40": "福岡県",
    "41": "佐賀県",
    "42": "長崎県",
    "43": "熊本県",
    "44": "大分県",
    "45": "宮崎県",
    "46": "鹿児島県",
    "47": "沖縄県",
}

jhsd_0004 = {
    "H": "入院時",
    "L": "退院時",
    "O": "外来時",
    "B": "手術前",
    "A": "手術後",
    "F": "最終",
}

jhsd_0005 = {"1": "疑いあり"}
